export const stories_list = state => state.stories_list;
export const games_list = state => state.games_list;
export const stories = state => state.stories;
export const node = (state) => state.node.current;
export const currentNode = state => state.currentNode;
export const node_prepared_to_delete = (state) => state.node_prepared_to_delete;
export const story_prepared_to_delete = (state) => state.story_prepared_to_delete;
export const is_loading = state => state.is_loading;
export const authorized = state => !(state.token === null);
export const token = state => state.token;
export const token_exp = state => state.token_exp;
export const current_error_msg = state => state.current_error_msg;